# SELECT DISTINCT
# C.ITEM_ID,
# C.ITEM_NAME
# FROM ITEM_INFO C
# JOIN ITEM_TREE P
# ON C.ITEM_ID = P.PARENT_ITEM_ID
SELECT
I.ITEM_ID,
I.ITEM_NAME
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE PARENT_ITEM_ID IS NULL