# -- 코드를 작성해주세요
# SELECT
# # FORAMT(MAX(LENGTH),2) AS MAX_LENGTH
# CONCAT(CAST(MAX(LENGTH) AS DECIMAL(10,2)), 'cm') AS MAX_LENGTH
# FROM FISH_INFO
SELECT CONCAT(MAX(LENGTH),'cm') as MAX_LENGTH
FROM FISH_INFO
