# -- 코드를 작성해주세요
# SELECT 
# I.ITEM_ID,
# I.ITEM_NAME,
# I.RARITY
# FROM ITEM_INFO I
# JOIN ITEM_TREE T
# ON I.ITEM_ID = T.ITEM_ID
# WHERE T.PARENT_ITEM_ID IS NOT NULL AND I.RARITY ='RARE'
# ORDER BY I.ITEM_ID DESC
SELECT 
    C.ITEM_ID,
    C.ITEM_NAME,
    C.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO P  -- 부모 아이템
    ON T.PARENT_ITEM_ID = P.ITEM_ID
JOIN ITEM_INFO C  -- 자식 아이템
    ON T.ITEM_ID = C.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC;
