SELECT
COUNT(*) AS FISH_COUNT
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
# WHERE N.FISH_TYPE = 0 OR N.FISH_TYPE = 1
# 틀린이유 :  문자열 "0", 이거나 "1"일수있다?
WHERE N.FISH_NAME IN ('BASS', 'SNAPPER');
# == WHERE N.FISH_NAME = 'BASS' OR N.FISH_NAME = 'SNAPPER'
