-- 코드를 작성해주세요
WITH MAX_FISH AS(
SELECT
    I.FISH_TYPE,
    MAX(I.LENGTH) AS MAX_FISH_LENGTH,
    N.FISH_NAME
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY I.FISH_TYPE,N.FISH_NAME
)
SELECT
I.ID,
M.FISH_NAME,
I.LENGTH
FROM FISH_INFO I
JOIN MAX_FISH M
ON I.FISH_TYPE = M.FISH_TYPE
WHERE M.MAX_FISH_LENGTH = I.LENGTH
ORDER BY ID ASC